# Generated by Django 3.1.7 on 2021-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthIDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='test@testing.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='num_of_otp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
