# Generated by Django 3.1.7 on 2021-10-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthIDApp', '0002_auto_20211009_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.PositiveIntegerField()),
                ('address_line1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_diagnose', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='aadhar',
            field=models.PositiveIntegerField(blank=True, default=12312321312),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='basic_medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('blood_group', models.TextField()),
                ('allergies', models.ManyToManyField(to='healthIDApp.Allergies')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthIDApp.disease')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthIDApp.surgery')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='basic_medical_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='healthIDApp.basic_medical'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthIDApp.address'),
        ),
    ]
