# Generated by Django 3.1.7 on 2021-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthIDApp', '0003_auto_20211010_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='is_current',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
