# Generated by Django 3.1.7 on 2021-10-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthIDApp', '0004_disease_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_medical',
            name='allergies',
        ),
    ]
