# Generated by Django 3.1.7 on 2021-10-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthIDApp', '0008_auto_20211011_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='is_communicatable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
