# Generated by Django 3.1.7 on 2021-10-12 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthIDApp', '0009_disease_is_communicatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthIDApp.address'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='num_of_otp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
