# Generated by Django 3.1.7 on 2021-10-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthIDApp', '0010_auto_20211012_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_of', to='healthIDApp.address'),
        ),
    ]
