# Generated by Django 3.1.7 on 2021-10-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthIDApp', '0011_auto_20211012_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='basic_medical_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basic_medical_of', to='healthIDApp.basic_medical'),
        ),
    ]
