# Generated by Django 3.1.7 on 2021-10-13 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthIDApp', '0012_auto_20211012_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('num_of_otp', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('organization_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_of_org', to='healthIDApp.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
